version: "3.8"

services:
  mysqldb:
    image: "mysql:8.1"
    restart: always
    ports:
      - 3306:3306
    networks:
      - virtual-threads-net
    environment:
      MYSQL_DATABASE: virtual_threads_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
  app:
    depends_on:
      - mysqldb
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - virtual-threads-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/virtual_threads_db?allowPublicKeyRetrieval=true
    volumes:
      - .m2:/root/.m2

volumes:
  db:

networks:
  virtual-threads-net: